//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public int ID { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public int CEDULA { get; set; }
        public string EMAIL { get; set; }
        public string TELEFONO { get; set; }
        public int TARJETA_CREDITO { get; set; }
        public decimal LIMITE_CREDITO { get; set; }
        public string TIPO_PERSONA { get; set; }
        public Nullable<bool> ESTADO { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
    }
}
