//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSPECCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INSPECCION()
        {
            this.RENTA = new HashSet<RENTA>();
        }
    
        public int ID { get; set; }
        public string CODIGO { get; set; }
        public int ID_VEHICULO { get; set; }
        public bool TIENE_RAYADURAS { get; set; }
        public int ID_CANTIDAD_COMBUSTIBLE { get; set; }
        public bool TIENE_GATO { get; set; }
        public bool TIENE_ROTURA_CRISTAL { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public bool GOMA_TRASERA_DERECHA { get; set; }
        public bool GOMA_TRASERA_IZQUIERDA { get; set; }
        public bool GOMA_DELANTERA_DERECHA { get; set; }
        public bool GOMA_DELANTERA_IZQUIERDA { get; set; }
        public bool GOMA_REPUESTO { get; set; }
    
        public virtual CANTIDAD_COMBUSTIBLE CANTIDAD_COMBUSTIBLE { get; set; }
        public virtual VEHICULO VEHICULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RENTA> RENTA { get; set; }
    }
}
