//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULO
    {
        public int ID { get; set; }
        public string DESCRIPCION { get; set; }
        public string NUMERO_CHASIS { get; set; }
        public string NUMERO_MOTOR { get; set; }
        public string NUMERO_PLACA { get; set; }
        public Nullable<int> TIPO_VEHICULO { get; set; }
        public Nullable<int> MODELO_VEHICULO { get; set; }
        public Nullable<int> COMBUSTIBLE { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
    
        public virtual COMBUSTIBLE_VEHICULO COMBUSTIBLE_VEHICULO { get; set; }
        public virtual MODELO_VEHICULO MODELO_VEHICULO1 { get; set; }
        public virtual TIPO_VEHICULO TIPO_VEHICULO1 { get; set; }
    }
}
